homework3
MastersAcademy/ruby-rails-course-2017 pull request #50
Opened 2017-11-13 03:29 UTC by victor-bert

2017-11-13 09:16 UTC, YuriiRudenko requested changes

2017-11-13 09:16 UTC, VeloKoder commented on homeworks/victor.bert_victor-bert/homework_3/institution.rb
> +	def menu;  puts "Waitress #{@name} bring menu to visitor"; true; end
Краще не використовувати такий запис.
Воно то працюватиме, але іншій людині такий код буде важко читати

2017-11-13 09:16 UTC, VeloKoder commented on homeworks/victor.bert_victor-bert/homework_3/institution.rb
> +	def menu;  puts "Waitress #{@name} bring menu to visitor"; true; end
В принципі, якщо у вас є attr_accessor, то @ можна не писати. Але страшного в цьому нічого немає

2017-11-13 09:16 UTC, VeloKoder commented on homeworks/victor.bert_victor-bert/homework_3/institution.rb
> +	def choose;    puts "Visitor #{@name.upcase} choose a table ##{table} and sit"; true; end
Яка мета повертання true?

2017-11-13 09:16 UTC, VeloKoder commented on homeworks/victor.bert_victor-bert/homework_3/institution.rb
> +	def choose;    puts "Visitor #{@name.upcase} choose a table ##{table} and sit"; true; end
В принципі, можна розбити на два методи, тоді кожен метод відповідатиме за окрему дію, це принцип розподілення ролей, про це говоритиметься на одній з подальших лекцій

2017-11-13 09:16 UTC, VeloKoder commented on homeworks/victor.bert_victor-bert/homework_3/institution.rb
> +	def goHome; puts 'Visitor returns to home!!!'; true; end
convention over configuration.
Імена змінних і методів - snake_case
імена констант - UPPERCASE
імена класів і модулів - CamelCase

2017-11-13 13:49 UTC, victor-bert commented on homeworks/victor.bert_victor-bert/homework_3/institution.rb
> +	def choose;    puts "Visitor #{@name.upcase} choose a table ##{table} and sit"; true; end
мета повернення тру для послыдовного визову методiв в однострочному видi
типу `visitor.choose && visitor.call && visitor.ask('menu') && visitor.make`

2017-11-13 14:17 UTC, VeloKoder commented on homeworks/victor.bert_victor-bert/homework_3/institution.rb
> +	def choose;    puts "Visitor #{@name.upcase} choose a table ##{table} and sit"; true; end
Для цього true не потрібен
Щоб пройшла строка `if a && b && c` достатньо, щоб кожен із них повертав не nil і не false

2017-11-13 14:18 UTC, VeloKoder commented on homeworks/victor.bert_victor-bert/homework_3/institution.rb
> +	def choose;    puts "Visitor #{@name.upcase} choose a table ##{table} and sit"; true; end
дякую за пояснення

2017-11-18 14:13 UTC, victor-bert commented
will be fixed in the next commit

2017-11-18 14:13 UTC, closed without merging