homework_4
MastersAcademy/ruby-rails-course-2017 pull request #67
Opened 2017-11-18 19:50 UTC by katatsu12

2017-11-18 19:50 UTC, katatsu12 commented
homework_4

2017-11-20 14:16 UTC, otmusic requested changes

2017-11-20 14:16 UTC, otmusic commented on homeworks/denis.zubritskiy_katatsu12/homework_4/mario_problem.rb
> +elsif height > 4
2 та 4 потрібно винести в константи типу
`MIN_PYRAMID_HEIGHT = 2`
`MAX_PYRAMID_HEIGHT = 4`

2017-11-20 14:16 UTC, otmusic commented on homeworks/denis.zubritskiy_katatsu12/homework_4/mario_problem.rb
> +if height < 2
в твоєму випадку замість `if else` краще писати
`return 'too low' if height < MIN_PYRAMID_HEIGHT`
`return 'too high' if height > MAX_PYRAMID_HEIGHT`

2017-11-20 14:16 UTC, otmusic commented on homeworks/denis.zubritskiy_katatsu12/homework_4/mario_problem.rb
> +  a = height
не бачу сенсу присвоювати змінній `a` значення `height `, використовуй відразу `height `. І на майбутнє краще не називати змінні `a, b` змінні повині містити якусь осмислену назву, щоб інший дев розумів, що ти написав

2017-11-20 14:16 UTC, otmusic commented on homeworks/denis.zubritskiy_katatsu12/homework_4/mario_problem.rb
> +    h = (" " * (a - b) + "@" * b)
також мені здається, що `@` краще також винести в константу

2017-11-20 17:42 UTC, merged