Homework_5
MastersAcademy/ruby-rails-course-2017 pull request #78
Opened 2017-11-24 16:20 UTC by sloonootop

2017-11-26 13:02 UTC, YuriiRudenko requested changes

2017-11-26 13:02 UTC, YuriiRudenko commented on homeworks/ievgen.saiko_sloonootop/homework_5/YourDialogue.rb
> +    @questions = questions
навіщо робити questions інстанс-змінною, якщо юзається вона тільки в цьому методі

2017-11-26 13:02 UTC, YuriiRudenko commented on homeworks/ievgen.saiko_sloonootop/homework_5/YourDialogue.rb
> +    @questions.each do |key, value|
те саме

2017-11-26 13:02 UTC, YuriiRudenko commented on homeworks/ievgen.saiko_sloonootop/homework_5/YourDialogue.rb
> +    @answers = Hash.new{}
достатньо так оголосити
`@answers = {}`

2017-11-27 16:07 UTC, sloonootop commented
updated with fixed file

2017-11-30 09:13 UTC, merged